# -*- coding: utf-8 -*-
"""Breast Cancer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYUJsbHhMtftOvgnFbyyFqICHnlQgUy8
"""

import pandas as pd

df=pd.read_csv('Breast_Cancer.csv')
df.describe()
print(df.describe())

df.info()

df.shape

df.isnull()
print(df.isnull())

df.columns

y=['Marital Status']

categorical_features=['Age','Tumor Size','Status']

X = df[categorical_features]
X.describe()

from sklearn.tree import DecisionTreeRegressor

#define model
Breast_cancer_model=DecisionTreeRegressor(random_state=1)

#fit model
Breast_cancer_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

print('making predictions for the following 3 breast cancer cases:')
print(X.head())
print('the predictions are')
print(Breast_cancer_model.predict(X.head()))