# -*- coding: utf-8 -*-
"""CM laptop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYc1sApxp1j4hhalLKSnRDh-0V-_Y8fz
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix


df = pd.read_csv('1.csv')

actual = df['CPU']
predicted = df['Price (Euros)']

cm = confusion_matrix(actual, predicted)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=sorted(actual.unique()),
            yticklabels=sorted(actual.unique()))
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()