# -*- coding: utf-8 -*-
"""data cluster

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2PO3qUerciOCm4JunRNTW-XMUZAo6JA
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

#Loan the dataset
iris = load_iris()
X = iris.data #Features
y = iris.target #Labels

#Split into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Initialize the model
model= RandomForestClassifier(n_estimators=100, random_state=42)

#Train the model
model.fit(x_train, y_train)

#Make predictions
y_pred = model.predict(x_test)

#Evaluate the model
accuracy=accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

#Optional: Predict on new data
sample=[[5.1, 3.5, 1.4, 0.2]]
prediction=model.predict(sample)
print("Prediction:", iris.target_names[prediction[0]])

import numpy as np
import matplotlib.pyplot as plt

x=[4,5,10,4,3,11,14,6,10,12]
y=[21,19,24,17,16,25,24,22,21,21]

plt.scatter(x,y)
plt.show()

#include euclidean distance and form dendrogram
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

x=[4,5,10,4,3,11,14,6,10,12]
y=[21,19,24,17,16,25,24,22,21,21]

data=list(zip(x,y))
linkage_data=linkage(data, method='ward',metric='euclidean')
dendrogram(linkage_data)
plt.show()