# -*- coding: utf-8 -*-
"""decision tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbDKpOPQe_kYEGZmaTAk6_DydaKfAMa-
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import pandas as pd

#step1: prepare the data
data={
    'outlook':['sunny','sunny','overcast','rain','rain'],
    'humidity':['high','normal','high','normal','normal'],
    'wind':['weak','weak','weak','weak','strong'],
    'playtennis':['no','yes','yes','yes','no']
}

df=pd.DataFrame(data)

#step2:convert categorical features to numbers

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for column in df.columns:
  df[column]=le.fit_transform(df[column])

# features and target
x=df[['outlook','humidity','wind']]
y=df['playtennis']


#step3:train the decision tree model
clf=DecisionTreeClassifier()
clf=clf.fit(x,y)

#step4: visualize the tree
import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
tree.plot_tree(clf, feature_names=['Outlook','Humidity','Wind'], class_names=['no','yes'], filled=True)

plt.show()