# -*- coding: utf-8 -*-
"""example4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPrG7Zbk0_GtsP_y7b4ZTo-Zn7-8pjyT
"""

# Predict the speed of a 10 years old car:
from scipy import stats

x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]

slope, intercept, r, p, std_err = stats.linregress(x, y)

def myfunc(x):
  return slope * x + intercept

speed = myfunc(10)

print(speed)