# -*- coding: utf-8 -*-
"""Example2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2c4DDp3aSf4C4TNMh6xQ6Jyw2KGKxL5
"""

import matplotlib.pyplot as plt
from scipy import stats
x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]

slope, intercept, r, p, std_err = stats.linregress(x, y)

def myfunc(x):
  return slope * x + intercept

mymodel = list(map(myfunc, x))

plt.scatter(x, y)
plt.plot(x, mymodel)
plt.show()