# -*- coding: utf-8 -*-
"""example3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11A-zMFJbvc6yUde8UFZlkd_-gQ5A1FAe
"""

from scipy import stats

x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]

slope, intercept, r, p, std_err = stats.linregress(x, y)

print(r)