# -*- coding: utf-8 -*-
"""example1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJfo8O8XuNXy1Gy6lBIHH1sdyc_XArPN
"""

import matplotlib.pyplot as plt
x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]

plt.scatter(x, y)
plt.show()

