# -*- coding: utf-8 -*-

"""initial regression of car data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QX172slJFy3t7Sd0rwnymEcYhIxcpLDb
"""

import pandas as pd
from sklearn import linear_model

df = pd.read_csv('newcar_data.csv')
print(df)

X=df[['weight','volume']]
y= df['co2_emmison']

regr=linear_model.LinearRegression()
regr.fit(X,y)

predictedco2=regr.predict([[2300,1.3]])

print(predictedco2)

#coefficient
print(regr.coef_)

#this values tells us that if the weight is increased by 1kg then the co2 emmison increased by 1.66 gm
#and if the engine size (volume ) is inc by 1cm3 then the co2 emmison increased by 4.595 gm

predictedco2=regr.predict([[3300,1.2]])
print(predictedco2)

