# -*- coding: utf-8 -*-
"""K-means

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQ2v0wLrWJmAPvzfGJ6KKjhH6QMD7603
"""

import matplotlib.pyplot as plt
x = [4, 5, 10, 4, 3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

#plt.scatter (x,y)
#plt.show()

from sys import modules


from sklearn.cluster import KMeans
data=list(zip(x,y))
inertias=[]

for i in range(1,11):
  model=KMeans(n_clusters=i)
  model.fit(data)
  inertias.append(model.inertia_)

#Loops through values of i from 1 to 10, each representing a different number of clusters (k).
#For each value of i:
#A KMeans model is created with i clusters.
#The model is fit to the data.
#The inertia (sum of squared distances between data points and their assigned cluster center) is recorded.
#inertias will store 10 values (one for each k), representing how well the data fits into that number of clusters.

#Combines the x and y coordinates into pairs, resulting in a list of 2D data points.
#Example: x = [1, 2, 3], y = [4, 5, 6] → data = [(1, 4), (2, 5), (3, 6)]

plt.plot(range(1,11),inertias, marker='o')
plt.title('Elbow method')
plt.xlabel('number of clusters')
plt.ylabel('inertias')
plt.show()