# -*- coding: utf-8 -*-
"""KMeans_example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noeRBbMUHQ-iaae56ezrVEY7B5re6AGQ
"""

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('ertiga_petrol_distance_data.csv')

plt.figure(figsize=(8,6))
plt.scatter(df['petrol_litres'],df['distance_traveled_km'], color='blue', alpha=0.7)
plt.title('Petrol Consumption vs Distance Traveled')
plt.xlabel('Petrol Consumption (Litres)')
plt.ylabel('Distance Traveled (Kilometers)')

plt.grid(True)
plt.show()

from sklearn.cluster import KMeans
data=list(zip(x,y))
inertias=[]

for i in range(1,11):
  model=KMeans(n_clusters=i)
  model.fit(df)
  inertias.append(model.inertia_)

plt.plot(range(1,11),inertias, marker='o')
plt.title('Elbow method')
plt.xlabel('number of clusters')
plt.ylabel('inertias')
plt.show()