# -*- coding: utf-8 -*-
"""logistic regression coefficient

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1amC1naHeP1v6wwGVjDf18G_WML066hfp
"""

import numpy as np
from sklearn import linear_model

#Reshaped for Logistic function.
X = np.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1,1)
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

logr = linear_model.LogisticRegression()
logr.fit(X,y)

log_odds = logr.coef_
odds = np.exp(log_odds)

print(odds)