# -*- coding: utf-8 -*-
"""ML data  validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qWwd2mk1RghhcsCLMLqsj8vO0IOriZy
"""

import numpy as np
from sklearn.model_selection import train_test_split
#example dataset with 10 samples and features
x=np.array([[i,i+1] for i in range(10)])
y=np.array([f"label_{i}" for i in range(10)]) #labels

#step 1: split into temp(80%) and test(20%)
x_temp, x_test, y_temp, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#step 2: split temp intpo train (75% of temp=60%) and val (25% of temp=20%)
x_train, x_val, y_train, y_val=train_test_split(x_temp,y_temp,test_size=0.25,random_state=42)

#show the shapes/sizes
print("x_train shape:",x_train.shape)
print("x_val shape:",x_val.shape)
print("x_test shape:",x_test.shape)

print("\nx_train:\n",x_train)
print("\ny_train:\n",y_train)

print("\nx_val:\n",x_val)
print("\ny_val:\n",y_val)

print("\nx_test:\n",x_test)
print("\ny_test:\n",y_test)

import numpy as np
from sklearn.model_selection import train_test_split
#example dataset with 20 samples and features
x=np.array([[i,i+1] for i in range(20)])
y=np.array([f"label_{i}" for i in range(20)]) #labels

#step 1: split into temp(80%) and test(20%)
x_temp, x_test, y_temp, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#step 2: split temp intpo train (75% of temp=60%) and val (25% of temp=20%)
x_train, x_val, y_train, y_val=train_test_split(x_temp,y_temp,test_size=0.25,random_state=42)

#show the shapes/sizes
print("x_train shape:",x_train.shape)
print("x_val shape:",x_val.shape)
print("x_test shape:",x_test.shape)

print("\nx_train:\n",x_train)
print("\ny_train:\n",y_train)

print("\nx_val:\n",x_val)
print("\ny_val:\n",y_val)

print("\nx_test:\n",x_test)
print("\ny_test:\n",y_test)