# -*- coding: utf-8 -*-
"""newcar dta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8HOVpwnN8HMUvxz8VDbMS3PMQs9BqnN
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

# Load the dataset
df = pd.read_csv('newcar_data.csv')
print(df.head())  # View the first few rows

# Define features and target variable
X = df[['weight', 'volume']]        # Features
y = df['co2_emmison']               # Target

# Create and train the model
regr = LinearRegression()
regr.fit(X, y)

# Make a prediction for a car with weight=2300kg and volume=1.3L
predicted_co2_1 = regr.predict([[2300, 1.3]])
print("Predicted CO2 (2300kg, 1.3L):", predicted_co2_1)

# Print coefficients
print("Coefficients:", regr.coef_)
print("Intercept:", regr.intercept_)

# Interpretation:
# If regr.coef_ = [1.66, 4.595], then:
# - Each 1kg increase in weight → +1.66 g/km CO₂
# - Each 1L (1000cm³) increase in volume → +4.595 g/km CO₂

# Another prediction for weight=3300kg and volume=1.2L
predicted_co2_2 = regr.predict([[3300, 1.2]])
print("Predicted CO2 (3300kg, 1.2L):", predicted_co2_2)

