# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRlU6ZecRUCSKENgoAiSsFHMFMQSEUd0
"""

import pandas as pd
from io import StringIO
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

# Simulate reading the data from the image
data = """
Carname,Color,Age,Speed,AutoPass
BMW,red,5,99,Y
Volvo,black,7,86,Y
VW,gray,8,87,N
VW,white,7,88,Y
Ford,white,2,111,Y
VW,white,17,86,Y
Tesla,red,2,103,Y
BMW,black,9,87,Y
Volvo,gray,4,94,N
Ford,white,11,78,N
Toyota,gray,12,77,N
VW,white,9,85,N
Toyota,blue,6,86,Y
"""

df = pd.read_csv(StringIO(data))

# --- Bar Plots ---

# 1. Carname Distribution
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='Carname', palette='viridis')
plt.title('Distribution of Car Brands')
plt.xlabel('Car Brand')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 2. Color Distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Color', palette='Set2')
plt.title('Distribution of Car Colors')
plt.xlabel('Color')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

# 3. AutoPass Distribution
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='AutoPass', palette='pastel')
plt.title('Distribution of AutoPass Status')
plt.xlabel('AutoPass')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

# 4. Average Speed by Car Brand
avg_speed_by_car = df.groupby('Carname')['Speed'].mean().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
avg_speed_by_car.plot(kind='bar', color='skyblue')
plt.title('Average Speed by Car Brand')
plt.xlabel('Car Brand')
plt.ylabel('Average Speed')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# --- Pie Plots ---

# 1. Proportion of Car Brands
car_counts = df['Carname'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(car_counts, labels=car_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Proportion of Car Brands')
plt.tight_layout()
plt.show()

# 2. Proportion of Car Colors
color_counts = df['Color'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(color_counts, labels=color_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('Set2'))
plt.title('Proportion of Car Colors')
plt.tight_layout()
plt.show()

# 3. Proportion of AutoPass Status
autopass_counts = df['AutoPass'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(autopass_counts, labels=['Yes' if x == 1 else 'No' for x in LabelEncoder().fit_transform(autopass_counts.index)],
        autopct='%1.1f%%', startangle=140, colors=['lightgreen', 'lightcoral'])
plt.title('Proportion of AutoPass Status')
plt.tight_layout()
plt.show()