# -*- coding: utf-8 -*-
"""training and testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sk-pyzPjSE1Y0zJXLMdAp9qpCHqSSLE7
"""

## Our data set illustrates 100 customers in a shop, and their shopping habits.
##The y axis represents the amount of money spent on the purchase.
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(2)

x=np.random.normal(3,1,100)
y=np.random.normal(150,40,100) / x

plt.scatter(x,y)
plt.show()

#Split Into Train/Test
#The training set should be a random selection of 80% of the original data.

#The testing set should be the remaining 20%.

train_x=x[:80]
train_y=y[:80]

test_x=x[80:]
test_y=y[80:]

#splay the Training Set
#Display the same scatter plot with the training set:

plt.scatter(train_x,train_y)
plt.show()

#Display the Testing Set
#To make sure the testing set is not completely different, we will take a look at the testing set as well.

plt.scatter(test_x,test_y)
plt.show()